### ISSUE TITLE
Tooltip not displaying for multiple questions

### ISSUE THREAD

**Issue by Si-WEHI** [ctsit/field_notes_display#5]
Hello, 

Great module, thanks for developing it.

I'm experiencing an issue where if I have a page with multiple question using the @FIELD-NOTES-DISPLAY="tooltip" command, only the last question in the series will actually display the help icon with the tooltip. Is this an issue with how I've set up the questions or could this be a bug? 

Many thanks,
Si

**Comment by tbembersimeao** [comment]
Nice catch @si-wehi, thanks! We implemented a fix for this bug and we will let you know as soon as the next release is available.

**Comment by marlycormar** [comment]
Hi @si-wehi, a fix for this bug has just been released! 
We will proceed to close this issue but please feel free to open a new one if you experience any inconsistency.

**Comment by Si-WEHI** [comment]
Wow you guys work fast! Thanks very much :) will give it a go!

**Comment by Si-WEHI** [comment]
Hi guys, just wondering what time frame I'd be looking at for the new version to be pushed through to REDCap external modules. Can't see any updates as yet.

**Comment by tbembersimeao** [comment]
@si-wehi I submitted the update request to REDCap Repo this morning. The new release should be available soon.

**Comment by tbembersimeao** [comment]
@si-wehi release 1.1.2 is available at [REDCap Repo](https://redcap.vanderbilt.edu/consortium/modules/).

**Comment by Si-WEHI** [comment]
@tbembersimeao thanks for the update, just confirming the update has been pushed through and "@FIELD-NOTES-DISPLAY="tooltip"" is now working on multiple fields. Thank you again for the quick fix.
